CREATE TYPE Level AS ENUM ('Trainee', 'Junior', 'Middle', 'Senior');

CREATE TABLE worker(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2),
    BIRTHDAY DATE CHECK (EXTRACT(YEAR FROM BIRTHDAY) > 1900),
    LEVEL Level NOT NULL,
    SALARY INT CHECK (SALARY >= 100 AND SALARY <= 100000)
);

CREATE TABLE client(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2)
);

CREATE TABLE project(
    ID SERIAL PRIMARY KEY,
    CLIENT_ID INT REFERENCES client(ID),
    START_DATE DATE,
    FINISH_DATE DATE CHECK (FINISH_DATE >= START_DATE + INTERVAL '1 month' AND FINISH_DATE <= START_DATE + INTERVAL '100 month')
);
